# **Señales 2D versus Matrices**

Antes del laboratorio 8 debemos repasar algunos conceptos de matrices que algo vimos en la primera parte. Traigan todo esto hecho para el jueves para poder seguir la clase! Pueden hacerlo en grupo, o no. En la clase solo veremos dudas. A programar!

In [2]:
# Importamos las bibliotecas necesarias
import cv2 #para imágenes, Open CV (Computer Vision)
import numpy as np
import matplotlib.pyplot as plt

## Ejercicio 1: 
a) Codifique las siguientes matrices $$A=\begin{pmatrix} 1 & -9 & \frac{1}{2} \\ 3 & 0 & 0\end{pmatrix} \;\;\; y \;\;\; B=\begin{pmatrix} 1 & -9 & \frac{1}{2} \\ 3 & 0 & 0 \\ 0 & 1 &2\end{pmatrix}$$

Además, extraiga la primera fila de $A$ y la segunda columna de $B$.

In [3]:
A=np.array([[1, -9,  1/2], [3, 0, 0]]) #A tiene 2 filas y 3 columnas
print(A)

print('Primera fila de A ', A[0,:]) # la primera fila de A


[[ 1.  -9.   0.5]
 [ 3.   0.   0. ]]
Primera fila de A  [ 1.  -9.   0.5]


In [4]:
B=np.array([[1, -9,  1/2], [3, 0, 0], [0,1,2]]) #completar
print(B)
print('Segunda columna de B', B[:,1]) #la segunda columna de B, pensar: porqué uso 1 en lugar de 2? y porqué me lo muestra en horizontal al resultado?

[[ 1.  -9.   0.5]
 [ 3.   0.   0. ]
 [ 0.   1.   2. ]]
Segunda columna de B [-9.  0.  1.]


b) Obtenga el tamaño (orden) y cantidad de elementos de $A$ y $B$. 

   Comando **shape** y **size**

In [ ]:
print("El orden de la matriz A es ", A.shape) #el método shape da el orden de A

print("La cantidad de elementos de la matriz A es", A.size) #el método size da la cantidad de elementos de A

El orden de la matriz A es  (2, 3)
La cantidad de elementos de la matriz A es 6


In [ ]:
B.shape[1] #Razonar: qué estoy obteniendo acá? si cambio el valor entre corchetes qué cambio?

3

In [ ]:
B[1].shape #Y en este caso qué estoy obteniendo acá? si cambio el valor entre corchetes que cambio?

(3,)

c) Indique el elemento $a_{12}$ de A y la primera fila de B.

In [ ]:
# Elemento a12 de A
print('El elemento a12 de A es ', A[0,1]) #Recordar que en Python la indexación comienza con 0

# Primera fila de B
print(B[0,:])

# También, de manera análoga, Primera fila de B:
print(B[0], B[0].shape)

print('Notar las nuevas dimensiones de los resultados')

El elemento a12 de A es  -9.0
[ 1.  -9.   0.5]
[ 1.  -9.   0.5] (3,)
Notar las nuevas dimensiones de los resultados


d) se puede hacer la suma (lugar a lugar) A+B? --> razonar por qué no

Modifiquemos la matriz $A$ agregando una fila al final.

In [ ]:
A2= np.array([A[0,:], A[1,:], [2, -3,9]]) #matriz modificada
print(A2)


[[ 1.  -9.   0.5]
 [ 3.   0.   0. ]
 [ 2.  -3.   9. ]]


In [ ]:
#Ahora si podemos sumar.
print('Suma de A2 + B', '\n', A2+B) #'\n', permite hacer un salto de línea
print('A2', '\n', A2)
print('B', '\n', B)
print('Suma de B + A2', '\n', B+A2)

Suma de A2 + B 
 [[  2. -18.   1.]
 [  6.   0.   0.]
 [  2.  -2.  11.]]
A2 
 [[ 1.  -9.   0.5]
 [ 3.   0.   0. ]
 [ 2.  -3.   9. ]]
B 
 [[ 1.  -9.   0.5]
 [ 3.   0.   0. ]
 [ 0.   1.   2. ]]
Suma de B + A2 
 [[  2. -18.   1.]
 [  6.   0.   0.]
 [  2.  -2.  11.]]


e) Transponer la matriz $A$

In [ ]:
# Matriz Transpuesta
At = np.transpose(A)
print(At)

[[ 1.   3. ]
 [-9.   0. ]
 [ 0.5  0. ]]


f) Calcule A./A, B./A2 k+A, k*A con k numero real cualquiera y A2 * B, elíja uno para cada operación

¿Que tipo de operación es cada una?


In [ ]:
div = A/A # divide lugar a lugar, qué significa esto? Razonar cómo sería hacerlo a mano.
print('Matriz A',  '\n', A)
print('Matriz A./A',  '\n', div)

print('\n','Matriz B./A2',  '\n', B/A2) #Razonar: cuál es el problema? Porqué nos da una advertencia python?

Matriz A 
 [[ 1.  -9.   0.5]
 [ 3.   0.   0. ]]
Matriz A./A 
 [[ 1.  1.  1.]
 [ 1. nan nan]]

 Matriz B./A2 
 [[ 1.          1.          1.        ]
 [ 1.                 nan         nan]
 [ 0.         -0.33333333  0.22222222]]


<ipython-input-11-f23c8597041b>:1: RuntimeWarning: invalid value encountered in true_divide
  div = A/A # divide lugar a lugar, qué significa esto? Razonar cómo sería hacerlo a mano.
<ipython-input-11-f23c8597041b>:5: RuntimeWarning: invalid value encountered in true_divide
  print('\n','Matriz B./A2',  '\n', B/A2) #Razonar: cuál es el problema? Porqué nos da una advertencia python?


In [ ]:
k= 2 #colocar cualquier número
S= k+A #suma lugar a lugar, qué significa esto?
P= k*A
print('Matriz A', '\n', A)
print('Matriz S', '\n',S)
print('Matriz P', '\n',P)

Matriz A 
 [[ 1.  -9.   0.5]
 [ 3.   0.   0. ]]
Matriz S 
 [[ 3.  -7.   2.5]
 [ 5.   2.   2. ]]
Matriz P 
 [[  2. -18.   1.]
 [  6.   0.   0.]]


In [ ]:
#Nos gustaría realizar la operación de multiplicar lugar a lugar los elementos de dos matrices.
#Pero no podemos hacerlo con A y B, dado que son de tamaño distintos, usamos A2.
A2*B #el operador * realiza la operación de multiplicar lugar a lugar.
print(A2*B) #Observen que nos devuelve una matriz.
#Repetir esta operación a mano, y razonar: cuál es la lógica?

[[ 1.   81.    0.25]
 [ 9.    0.    0.  ]
 [ 0.   -3.   18.  ]]


## Ejercicio 2: Matrices Especiales
- con sólo unos: np.ones((m,n))
- con sólo ceros: np.zeros((m,n))
- una matriz con una distribución aleatoria con valores entre 0 y 1:  np.random.random((m,n))
- una matriz con una distribución uniforme con valores entre vmin y vmax:  np.random.uniform(vmin,vmax,(m,n))


a) Genere una matriz H con ceros de 4 filas y 3 columnas y otra matriz J con unos de 3 filas y 3 columnas

In [ ]:
#Matriz H con unos de 4 filas y 3 columnas y otra matriz J con unos de 3 filas y 3 columnas

H=np.zeros((4,3))
J=np.ones((3,3))

print(H)
print(J)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


b) Genere una matriz R de números aleatorios entre 0 y 1 de 62x186 
y genere una matriz A1 con números aleatorios entre 1 y 2 de 2x3.

In [ ]:
R=np.random.random((62,186))
print(R)

[[0.25294935 0.29710858 0.01125424 ... 0.70831666 0.15602082 0.27233619]
 [0.04427511 0.69603194 0.12445577 ... 0.07461912 0.09397308 0.13177884]
 [0.39662802 0.66696644 0.60919142 ... 0.16018398 0.28353069 0.90180099]
 ...
 [0.9472278  0.98432221 0.14281656 ... 0.59357421 0.0599055  0.12630667]
 [0.61811262 0.07364056 0.3115103  ... 0.71041585 0.88712957 0.57198541]
 [0.56960458 0.58335937 0.35820376 ... 0.32507687 0.9968273  0.96539833]]


In [ ]:
A1=np.matrix(np.random.uniform(1,2,(2,3))) #uniform permite generar números aleatorios entre un mínimo y un máximo, matrix permite convertir el array generado con uniform en una matriz
print(A1)

[[1.43686132 1.88770673 1.27536885]
 [1.25979491 1.65976778 1.13815396]]


c) Genere una matriz R de numeros enteros iguales (i) de 2x3 e imprima la suma de R + A1

In [ ]:
i=5
R=i*np.ones((2,3))
print(R + A1)

[[6.86892769 6.69678953 6.94142945]
 [6.85130425 6.63838342 6.22311296]]


## Ejercicio 3:

Construya 3 vectores columna de 20 elementos cada uno, de modo que la diferencia entre
dos elementos consecutivos sea 0.4 para el primero, 0.6 para el segundo y 2 para el tercero.    
a) Construya una matriz de 20 filas por 3 columnas con los vectores definidos anteriormente.

In [ ]:
#Construímos los 3 vectores 

v1 = np.arange(1,1+0.4*20,0.4)
v2 = np.arange(1,1+0.6*20,0.6)
v3 = np.arange(1,1+2*20,2)

#Prueben hacer lo mismo con otras formas de construir vectores

print('vector 1 ','\n', v1,'\n', 'de orden', v1.shape)
print('vector 2 ','\n', v2,'\n', 'de orden', v2.shape)
print('vector 3 ','\n', v3,'\n', 'de orden', v3.shape)

#armamos una matriz M con 3 columnas y 20 filas. Ubicamos los vectores generados en cada columna 

M = np.zeros((20,3))
M[:,0]=v1
M[:,1]=v2
M[:,2]=v3
print('Matriz M construida con vectores v1, v2 y v3', '\n', M)

vector 1  
 [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5.  5.4 5.8 6.2 6.6 7.  7.4 7.8
 8.2 8.6] 
 de orden (20,)
vector 2  
 [ 1.   1.6  2.2  2.8  3.4  4.   4.6  5.2  5.8  6.4  7.   7.6  8.2  8.8
  9.4 10.  10.6 11.2 11.8 12.4] 
 de orden (20,)
vector 3  
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39] 
 de orden (20,)
Matriz M construida con vectores v1, v2 y v3 
 [[ 1.   1.   1. ]
 [ 1.4  1.6  3. ]
 [ 1.8  2.2  5. ]
 [ 2.2  2.8  7. ]
 [ 2.6  3.4  9. ]
 [ 3.   4.  11. ]
 [ 3.4  4.6 13. ]
 [ 3.8  5.2 15. ]
 [ 4.2  5.8 17. ]
 [ 4.6  6.4 19. ]
 [ 5.   7.  21. ]
 [ 5.4  7.6 23. ]
 [ 5.8  8.2 25. ]
 [ 6.2  8.8 27. ]
 [ 6.6  9.4 29. ]
 [ 7.  10.  31. ]
 [ 7.4 10.6 33. ]
 [ 7.8 11.2 35. ]
 [ 8.2 11.8 37. ]
 [ 8.6 12.4 39. ]]


 b) Halle el máximo de la matriz y ubique en qué posición se encuentra.

In [ ]:
maxM = np.amax(M)
print('El máximo de la matriz M es', maxM)
posicionMax = np.where(M == maxM) #primer elemento es la posición en filas, segundo elemento posición en columnas. Siempre tener en cuenta que la indexación de python empieza en 0
print('Se encuentra en la fila', posicionMax[0]+1, 'columna', posicionMax[1]+1) 

El máximo de la matriz M es 39.0
Se encuentra en la fila [20] columna [3]


Y el mínimo? Cómo lo encuentro? Y su ubicación? Hay un solo mínimo?

In [ ]:
minM = np.amin(M)
print('El mínimo de la matriz M es', minM)
posicionMin = np.where(M == minM) #primer elemento es la posición en filas, segundo elemento posición en columnas. Siempre tener en cuenta que la indexación de python empieza en 0
print('Se encuentra en las filas', posicionMin[0]+1, 'columnas', posicionMin[1]+1, 'respectivamente')

El mínimo de la matriz M es 1.0
Se encuentra en las filas [1 1 1] columnas [1 2 3] respectivamente


c) Indique una SUBMATRIZ que tenga de las filas 5 hasta la 10 (no inclusive) y de las columnas 0 a la 2 (no inclusive) de Matriz

In [ ]:
SUBMATRIZ=M[5:10,0:2] #Repasar a conciencia, muchos tuvieron problemas con esto en el parcial!
print(SUBMATRIZ,'\n', 'Dimensiones de SUBMATRIZ: ', SUBMATRIZ.shape )

[[3.  4. ]
 [3.4 4.6]
 [3.8 5.2]
 [4.2 5.8]
 [4.6 6.4]] 
 Dimensiones de SUBMATRIZ:  (5, 2)


d) Indique el elemento de la fila 4, columna 2 de la submatriz 

In [ ]:
SUBMATRIZ[3,1]

5.800000000000001

e) Comparar valor lugar a lugar de 2 matrices del mismo tamaño.

In [ ]:
R2= np.matrix(np.random.uniform(1,39,(20,3)))
R2[5:10,0:2]=SUBMATRIZ
(R2[:] == M[:]) #Comparación lugar a lugar

matrix([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [ True,  True, False],
        [ True,  True, False],
        [ True,  True, False],
        [ True,  True, False],
        [ True,  True, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])

f) Comparar una fila de la matriz contra un escalar cualquiera y guardar el resultado en una variable

In [ ]:
v=5
fila=2
Q = M[fila] == v #resultado de la comparación de la fila de la matriz M contra un escalar
print(Q)

[False False  True]


# **Ejercicio 4: Tipo de Datos**

* **int:** enteros: 
>>**int8:** Enteros con signo en el rango [-128;127] (8 bits)              
>>**int16:** Enteros con signo en el rango [-32768;32767] (16 bits)   
>>**uint8:** Enteros sin signo en el rango [0;255] (8 bits) 256=2^8  
>>**uint16:** Enteros sin signo en el rango [0;65535] (16 bits)   
>>>>sin signo implica que ---> no vamos a obtener números negativos 
* **float:** coma flotante, decimales        
* **bool:** booleanos (true, false)        
* **complex:** complejos     



a) Qué tipo de datos tienen las matrices M y A?

In [ ]:
# tipo de datos matriz M
print('Tipo de datos de la matriz M', M.dtype)

# tipo de datos matriz A?
print('Tipo de datos de la matriz A', A.dtype)


Tipo de datos de la matriz M float64
Tipo de datos de la matriz A float64


b) Qué tipo de datos tiene el resultado Q (guardado anteriormente)?

In [ ]:
print(Q.dtype)

bool


c) Dado un número negativo con decimales:

*   Qué tipo de dato es? 
*   Converitirlo al tipo de datos uint8
*   Si se convierte nuevamente al tipo de dato original, vuelve al mismo valor? Por qué?

In [ ]:
#Para números
b=-72.0
print(type(b)) #tipo de dato de b
c=np.uint8(b) #convierto b a tipo de dato uint8
print(c)  #imprimo b convertido a uint8, no es el mismo valor! por qué?
#float(c)  #vuelve al mismo valor?


<class 'float'>
184


d) Convertir los valores de la matriz A:
A tipo de dato uint8
A tipo de dato complex128

In [ ]:
#Para matrices
print('Matriz A', '\n', A)
A_uint8= A.astype(np.uint8)
print('Matriz A_uint8', '\n', A_uint8)
A_complex=A.astype(np.complex128)
print('Matriz A_complex', '\n', A_complex) 

A_uint8_I=A_uint8.astype(np.float64)
print('Matriz A_uint8 vuelta a float64', '\n', A_uint8_I)
A_complex_I=A_complex.astype(np.float64)
print('Matriz A_complex vuelta a float64', '\n', A_complex_I) #Interpretar la advertencia

Matriz A 
 [[ 1.  -9.   0.5]
 [ 3.   0.   0. ]]
Matriz A_uint8 
 [[  1 247   0]
 [  3   0   0]]
Matriz A_complex 
 [[ 1. +0.j -9. +0.j  0.5+0.j]
 [ 3. +0.j  0. +0.j  0. +0.j]]
Matriz A_uint8 vuelta a float64 
 [[  1. 247.   0.]
 [  3.   0.   0.]]
Matriz A_complex vuelta a float64 
 [[ 1.  -9.   0.5]
 [ 3.   0.   0. ]]


<ipython-input-73-233248b0de5e>:10: ComplexWarning: Casting complex values to real discards the imaginary part
  A_complex_I=A_complex.astype(np.float64)


e) Crear matriz B1 con los datos de la matriz B convertidos a uint8. Luego realizar la siguiente comparación:


*   Sumar A2 + B
*   sumar A2 + B1

Dan el mismo resultado? Por qué?



In [ ]:
print(B.dtype) #busco el tipo de dato de B
B1= B.astype(np.uint8) #convierto los valores de la matriz B a uint8 y guardo el resultado en B1

print('B', '\n', B)
print('B1', '\n', B1) #las matrices tienen valores diferentes


print('A2 + B', '\n', A2 + B)
print('A2 + B1', '\n', A2 + B1) #las sumas dan valores diferentes. Interpretar.

float64
float64
B 
 [[ 1.  -9.   0.5]
 [ 3.   0.   0. ]
 [ 0.   1.   2. ]]
B1 
 [[  1 247   0]
 [  3   0   0]
 [  0   1   2]]
A2 + B 
 [[  2. -18.   1.]
 [  6.   0.   0.]
 [  2.  -2.  11.]]
A2 + B1 
 [[  2.  238.    0.5]
 [  6.    0.    0. ]
 [  2.   -2.   11. ]]
